# Permission: None
#
#
# Path variable:
# - billId: int
#
# Request params:
# - resultCode: int



GET http://localhost:8080/payment/command/api/bill/pay/complete/2?partnerCode=MOMOO41P20220925&orderId=096b1020-1601-40dc-b2db-9ab505f9f50c&requestId=7cf25c59-34f0-4e55-bf6c-bcb3ddad6c89&amount=1200000&orderInfo=M%C3%A3+ng%C6%B0%E1%BB%9Di+d%C3%B9ng%3A+1%2C+m%C3%A3+%C4%91%C6%A1n+h%C3%A0ng%3A+3&orderType=momo_wallet&transId=1684334065948&resultCode=1006&message=Transaction+denied+by+user.&payType=&responseTime=1684334066341&extraData=&signature=4cdb0109bcb882a747bdffbf59ff6b30c6c8df51994db5cd483c2cc6d220b69a
Content-Type: application/json